# Generated by LazyNix - DO NOT EDIT MANUALLY
# This file is automatically generated from lazynix.yaml
# To make changes, edit lazynix.yaml and run: lnix develop

{
  description = "DevShell generated by LazyNix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        stablePackages = import nixpkgs {
          inherit system;
          config.allowUnfree = false;
        };
        unstablePackages = import nixpkgs-unstable {
          inherit system;
          config.allowUnfree = false;
        };
      in
      {
        devShells.default = stablePackages.mkShell {
          buildInputs = [
            # Stable packages
            stablePackages.cargo
            stablePackages.rustc
            stablePackages.clippy
            stablePackages.rustfmt
            stablePackages.rust-analyzer
          ];

          shellHook = ''
            echo "tzt dev environment: $(rustc --version)"

if [ "$LAZYNIX_TEST_MODE" = "1" ]; then
TESTS_FAILED=0
TESTS_PASSED=0

echo "Running tests..."
echo "================="

for test_cmd in \
        "cargo build" \
        "cargo fmt --check" \
        "cargo clippy -- --deny warnings" \
        "cargo test"
do
    echo ""
    echo "Running: $test_cmd"
    echo "---"
    if bash -c "$test_cmd"; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo "[PASS] $test_cmd"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo "[FAIL] $test_cmd"
    fi
done

echo ""
echo "================="
echo "Test Results: $TESTS_PASSED passed, $TESTS_FAILED failed"

if [ $TESTS_FAILED -gt 0 ]; then
    exit 1
fi
fi
          '';
        };
      }
    );
}
