use clap::{Arg, Command, ArgMatches};

pub(crate) fn command_factory () -> ArgMatches {
    Command::new("timezone_converter")
        .version("1.0")
        .author("Your Name <your.email@example.com>")
        .about("Converts time between time zones")
        .arg(Arg::new("time")
            .short('T')
            .long("time")
            .value_name("TIME")
            .help("Time in the format YYYY-MM-DD HH:MM:SS")
            .required(true)
        )
        .arg(Arg::new("from_timezone")
            .short('f')
            .long("from")
            .value_name("FROM_TIMEZONE")
            .help("The original timezone (e.g., America/New_York)")
            .required(true)
        )
        .arg(Arg::new("to_timezone")
            .short('t')
            .long("to")
            .value_name("TO_TIMEZONE")
            .help("The target timezone (e.g., Asia/Tokyo)")
            .required(true)
        )
        .get_matches()
}